// Fill out your copyright notice in the Description page of Project Settings.


#include "func_lib/FInputHelper.h"


FInputHelper::FInputHelper()
{
}

FInputHelper::~FInputHelper()
{
}

const TMap<FString, FString> FInputHelper::KeyConversionMap = {
	{"A", "A_Key"},
	{"B", "B_Key"},
	{"C", "C_Key"},
	{"D","D_Key"},
	{"E","E_Key"},
	{"F","F_Key"},
	{"G","G_Key"},
	{"H","H_Key"},
	{"I","I_Key"},
	{"J","J_Key"},
	{"K","K_Key"},
	{"L","L_Key"},
	{"M","M_Key"},
	{"N","N_Key"},
	{"O","O_Key"},
	{"P","P_Key"},
	{"Q","Q_Key"},
	{"R","R_Key"},
	{"S","S_Key"},
	{"T","T_Key"},
	{"U","U_Key"},
	{"V","V_Key"},
	{"W","W_Key"},
	{"X","X_Key"},
	{"Y","Y_Key"},
	{"Z","Z_Key"},
	{"Left","Arrow_Left_Key"},
	{"Right","Arrow_Right_Key"},
	{"Up","Arrow_Up_Key"},
	{"Down","Arrow_Down_Key"},
	{"Zero","0_Key"},
	{"1","1_Key"},
	{"2","2_Key"},
	{"3","3_Key"},
	{"4","4_Key"},
	{"5","5_Key"},
	{"6","6_Key"},
	{"7","7_Key"},
	{"8","8_Key"},
	{"9","9_Key"},
	{"Escape","Esc_Key"},
	{"Space Bar","Space_Key"},
	{"Page Up","Page_Up_Key"},
	{"Page Down","Page_Down_Key"},
	{"End","End_Key"},
	{"Home","Home_Key"},
	{"Insert","Insert_Key"},
	{"Delete","Del_Key"},
	{"F1","F1_Key"},
	{"F2","F2_Key"},
	{"F3","F3_Key"},
	{"F4","F4_Key"},
	{"F5","F5_Key"},
	{"F6","F6_Key"},
	{"F7","F7_Key"},
	{"F8","F8_Key"},
	{"F9","F9_Key"},
	{"F10","F10_Key"},
	{"F11","F11_Key"},
	{"F12","F12_Key"},
	{"Left Shift","Shift_Key"},
	{"Right Shift","Shift_Key"},
	{"Left Ctrl","Ctrl_Key"},
	{"Right Ctrl","Ctrl_Key"},
	{"Left Alt","Alt_Key"},
	{"Right Alt","Alt_Key"},
	{"Left Cmd","Command_Key"},
	{"Right Cmd","Command_Key"},
	{"Semicolon","Semicolon_Key"},
	{"Slash","Slash_Key"},
	{"BackSpace","Backspace_Key"},
	{"Left Bracket","Bracket_Left_Key"},
	{"Right Bracket","Bracket_Right_Key"},
	{"Caps Lock", "Caps_Lock_Key"},
	{"Enter", "Enter_Key"},
	{"Left Mouse Button", "Mouse_Left_Key"},
	{"Right Mouse Button", "Mouse_Right_Key"},
	{"Middle Mouse Button", "Mouse_Middle_Key"},
	{"Thumb Mouse Button", "Mouse_Simple_Key"},
	{"Thumb Mouse Button 2", "Mouse_Simple_Key"},
	{"Num Lock", "Num_Lock_Key"}
};